### ISSUE TITLE
Pas ouf le site

### ISSUE THREAD

**Issue by FloDuFnaF** [Rroq1/Rroq1.github.io#1]
Faut faire quelque chose chef, y'a un blem avec ton site on dirait wikipédia 2012, stp bouge toi t'es pas actif de fou mec

**Comment by Rroq1** [comment]
csc

**Comment by FloDuFnaF** [comment]
ok mec ratio

**Comment by Rroq1** [comment]
Bonne soirée

**Comment by FloDuFnaF** [comment]
ftg
